// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResilienceOps.Api.Data;

#nullable disable

namespace ResilienceOps.Api.Data.Migrations
{
    [DbContext(typeof(ResilienceOpsDbContext))]
    [Migration("20260719132315_AddMitigationActions")]
    partial class AddMitigationActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("ResilienceOps.Api.Features.Mitigations.MitigationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("DueDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.HasIndex("RiskId", "Status");

                    b.ToTable("MitigationActions", (string)null);
                });

            modelBuilder.Entity("ResilienceOps.Api.Features.Risks.RiskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Risks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0894902-f420-4f75-bf42-d9678de1fb5d"),
                            CreatedUtc = 1784444400000L,
                            Description = "Loss of the identity provider could prevent employees from accessing critical systems.",
                            Severity = "Critical",
                            Status = "Open",
                            Title = "Identity provider outage"
                        },
                        new
                        {
                            Id = new Guid("82a22a45-56b0-437e-b65c-cc6d94e99e14"),
                            CreatedUtc = 1784444700000L,
                            Description = "Unclear ownership may delay escalation of high-impact operational incidents.",
                            Severity = "High",
                            Status = "Open",
                            Title = "Delayed incident escalation"
                        });
                });

            modelBuilder.Entity("ResilienceOps.Api.Features.Mitigations.MitigationAction", b =>
                {
                    b.HasOne("ResilienceOps.Api.Features.Risks.RiskItem", null)
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
